version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      formatting-updates:
        patterns:
          - '@cspell/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'prettier'
      nx:
        patterns:
          - '@babel/core'
          - '@babel/preset-react'
          - '@nx/*'
          - 'babel-jest'
          - 'nx'
      react:
        patterns:
          - 'react'
          - 'react-dom'
      types:
        patterns:
          - '@types/*'
