FROM nginx
RUN rm -drf /usr/share/nginx/html/50x.html
RUN rm -drf /etc/nginx/conf.d/default.conf
COPY dist/apps/web/android-chrome-192x192.png /usr/share/nginx/html
COPY dist/apps/web/android-chrome-512x512.png /usr/share/nginx/html
COPY dist/apps/web/apple-touch-icon.png /usr/share/nginx/html
COPY dist/apps/web/favicon-16x16.png /usr/share/nginx/html
COPY dist/apps/web/favicon-32x32.png /usr/share/nginx/html
COPY dist/apps/web/site.webmanifest /usr/share/nginx/html
COPY dist/apps/web/index.html /usr/share/nginx/html
COPY dist/apps/web/assets /usr/share/nginx/html/assets
COPY nginx.conf /etc/nginx/conf.d