services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - /Users/dgw/markdown-memory-run/daily:/usr/share/nginx/html/daily
      - /Users/dgw/markdown-memory-run/notes:/usr/share/nginx/html/notes
      - /Users/dgw/markdown-memory-run/images:/usr/share/nginx/html/images
